version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: compiler.Dockerfile
    container_name: nearbyassist-compiler
    volumes:
      - ./bin:/app/bin
    command: sh -c "cp /app/nearbyassist.exe /app/bin/"

volumes:
  bin:
