version: '3'

services:
  db:
    image: mysql
    container_name: nearbyassist-dev-db
    restart: on-failure
    env_file:
      - "./.db.env"
    expose:
      - '3306'
    ports:
      - "3307:3306"
    volumes:
      - "./internal/db/migrations/20231231015242_init.up.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
    networks:
      - nearbyassist-dev

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nearbyassist-dev-server
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - nearbyassist-dev
    volumes:
      - "./store:/store"

networks:
  nearbyassist-dev:

volumes:
  store:
