CREATE TABLE IF NOT EXISTS User (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    emailHash VARCHAR(64) NOT NULL,
    imageUrl VARCHAR(255),
    verified TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not verified, 1: verified',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX(id, name, emailHash)
);

CREATE TABLE IF NOT EXISTS Vendor (
    id VARCHAR(255) NOT NULL,
    vendorId VARCHAR(255) NOT NULL,
    rating Decimal(5,1) NOT NULL DEFAULT 0.0,
    job VARCHAR(255) NOT NULL,
    restricted TINYINT(1) NOT NULL DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(vendorId) REFERENCES User(id),
    INDEX(id, vendorId, job)
);

CREATE TABLE IF NOT EXISTS Admin (
    id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role Enum('admin', 'staff') NOT NULL DEFAULT 'staff',
    usernameHash VARCHAR(64) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    INDEX(id, usernameHash, role)
);

CREATE TABLE IF NOT EXISTS Session (
    id VARCHAR(255) NOT NULL,
    refreshToken VARCHAR(255) NOT NULL,
    status Enum('online', 'offline') NOT NULL DEFAULT 'online',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT unique_refreshToken_online UNIQUE (refreshToken, (CASE WHEN status = 'online' THEN 1 ELSE NULL END)),
    INDEX(refreshToken, status)
);

CREATE TABLE IF NOT EXISTS Blacklist (
    id VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    INDEX(token)
);

CREATE TABLE IF NOT EXISTS PublicKey (
    id VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    pem TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(owner) REFERENCES User(id),
    INDEX(id, owner)
);

CREATE TABLE IF NOT EXISTS PrivateKey (
    id VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    pem TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(owner) REFERENCES User(id),
    INDEX(id, owner)
);

CREATE TABLE IF NOT EXISTS Tag (
    id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    INDEX(id, title)
);

CREATE TABLE IF NOT EXISTS Service (
    id VARCHAR(255) NOT NULL,
    vendorId VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    rate Double NOT NULL,
    latitude Decimal(12, 10) NOT NULL,
    longitude Decimal(13, 10) NOT NULL,
    signature VARCHAR(64) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(vendorId) REFERENCES User(id),
    INDEX(id, vendorId, signature)
);

CREATE TABLE IF NOT EXISTS SavedService (
    id VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL,
    serviceId VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(userId) REFERENCES User(id),
    FOREIGN KEY(serviceId) REFERENCES Service(id),
    INDEX(id, userId, serviceId)
);

CREATE TABLE IF NOT EXISTS ServiceTag (
    id VARCHAR(255) NOT NULL,
    serviceId VARCHAR(255) NOT NULL,
    tagId VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(serviceId) REFERENCES Service(id) ON DELETE CASCADE,
    FOREIGN KEY(tagId) REFERENCES Tag(id),
    INDEX(id, serviceId, tagId)
);

CREATE TABLE IF NOT EXISTS Message (
    id VARCHAR(255) NOT NULL,
    sender VARCHAR(255) NOT NULL,
    receiver VARCHAR(255) NOT NULL,
    content Text NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(sender) REFERENCES User(id),
    FOREIGN KEY(receiver) REFERENCES User(id),
    INDEX(id, sender, receiver)
);

CREATE TABLE IF NOT EXISTS ServicePhoto (
    id VARCHAR(255) NOT NULL,
    serviceId VARCHAR(255) NOT NULL,
    vendorId VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(serviceId) REFERENCES Service(id) ON DELETE CASCADE,
    FOREIGN KEY(vendorId) REFERENCES User(id) ON DELETE CASCADE,
    INDEX(id, serviceId, vendorId)
);

CREATE TABLE IF NOT EXISTS IdentityVerification (
    id VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    idType VARCHAR(255) NOT NULL,
    idNumber VARCHAR(255) NOT NULL,
    frontIdImageUrl VARCHAR(255) NOT NULL,
    backIdImageUrl VARCHAR(255) NOT NULL,
    faceImageUrl VARCHAR(255) NOT NULL,
    status Enum('pending', 'rejected', 'approved') NOT NULL DEFAULT 'pending',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id, userId, idType),
    FOREIGN KEY(userId) REFERENCES User(id),
    INDEX(id)
);

CREATE TABLE IF NOT EXISTS VendorComplaint (
    id VARCHAR(255) NOT NULL,
    vendorId VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content Text NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(vendorId) REFERENCES User(id) ON DELETE CASCADE,
    INDEX(id, vendorId)
);

CREATE TABLE IF NOT EXISTS SystemComplaint (
    id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    detail Text NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    INDEX(id, title)
);

CREATE TABLE IF NOT EXISTS SystemComplaintImage (
    id VARCHAR(255) NOT NULL,
    complaintId VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(complaintId) REFERENCES SystemComplaint(id),
    INDEX(id, complaintId)
);

CREATE TABLE IF NOT EXISTS Review (
    id VARCHAR(255) NOT NULL,
    serviceId VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(serviceId) REFERENCES Service(id) ON DELETE CASCADE,
    INDEX(id, serviceId)
);

CREATE TABLE IF NOT EXISTS Transaction (
    id VARCHAR(255) NOT NULL,
    vendorId VARCHAR(255) NOT NULL,
    clientId VARCHAR(255) NOT NULL,
    serviceId VARCHAR(255) NOT NULL,
    status Enum('pending', 'ongoing', 'done', 'cancelled') NOT NULL DEFAULT 'pending',
    employmentType Enum('arawan', 'pakyaw') NOT NULL DEFAULT 'pakyaw',
    cost DOUBLE NOT NULL,
    startDate TIMESTAMP NOT NULL,
    endDate TIMESTAMP NOT NULL,
    isReviewed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not reviewed, 1: reviewed',
    isReported TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not reported, 1: reported',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(vendorId) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY(serviceId) REFERENCES Service(id) ON DELETE CASCADE,
    FOREIGN KEY(clientId) REFERENCES User(id),
    INDEX(id)
);

CREATE TABLE IF NOT EXISTS Application (
    id VARCHAR(255) NOT NULL,
    applicantId VARCHAR(255) NOT NULL UNIQUE,
    job VARCHAR(255) NOT NULL,
    status Enum('pending', 'rejected', 'approved') NOT NULL DEFAULT 'pending',
    supportingDocumentUrl VARCHAR(255) NOT NULL,
    policeClearanceUrl VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(applicantId) REFERENCES User(id)
);

DELIMITER //

CREATE TRIGGER update_vendor_rating
AFTER INSERT ON Review
FOR EACH ROW
BEGIN
    DECLARE avg_rating DECIMAL(5,1);
    
    SELECT ROUND(AVG(rating), 1) INTO avg_rating
    FROM Review
    WHERE serviceId = NEW.serviceId;

    UPDATE Vendor
    SET rating = avg_rating
    WHERE vendorId = (SELECT vendorId FROM Service WHERE id = NEW.serviceId);
END //

DELIMITER ;
