DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS Service;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS Complaint;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Vendor;
DROP TABLE IF EXISTS User;
