// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "nearbyassist/views/layout"

func AccountDeletionInstructions() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"max-w-4xl mx-auto py-10 px-4 sm:px-6 lg:px-8\"><header class=\"text-center mb-8\"><h1 class=\"text-3xl font-bold text-gray-900\">Account Deletion Instructions</h1><p class=\"text-gray-600 mt-2\">Updated At: <span>November 21, 2024</span></p></header><section class=\"bg-white shadow-md rounded-lg p-6\"><h2 class=\"text-2xl font-semibold mb-4 mt-6\">1. Go to <strong>Settings</strong></h2><p>You can find the settings in <strong>account section -> account settings -> settings</strong></p><div class=\"flex gap-4\"><img class=\"outline outline-1\" src=\"/public/account_deletion3.png\" alt=\"app screenshot\"> <img class=\"outline outline-1\" src=\"/public/account_deletion2.png\" alt=\"app screenshot\"></div><h2 class=\"text-2xl font-semibold mb-4 mt-6\">2. Select <strong>Delete Account</strong></h2><p>This option can be found at the bottom of the page highlighted <strong class=\"text-red-500\">red</strong>. This action is not reversible, so <strong>read carefully</strong>. If sure, tap on <strong>continue</strong>.</p><img class=\"outline outline-1\" src=\"/public/account_deletion1.png\" alt=\"app screenshot\"></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.NoLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
